addCustomer:
  image: add-customer-image
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers
        method: post
        cors: true

deleteCustomerById:
  image: delete-customer-image
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/{id}
        method: delete

findAllCustomers:
  image: find-all-customers-image
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers
        method: get

findCustomerByCPF:
  image: find-customer-by-cpf-image
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/cpf/{cpf}
        method: get

findCustomerById:
  image: find-customer-by-id-image
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/{id}
        method: get

updateCustomerById:
  image: update-customer-image
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/{id}
        method: put



